call git clone --branch 0.0.3 git@github.com:AlephVault/unity-support.git  ..\unity-support
call git clone --branch 0.0.1 git@github.com:AlephVault/unity-support-generic.git ..\unity-support-generic
call git clone --branch 0.0.2 git@github.com:AlephVault/unity-boilerplates.git ..\unity-boilerplates
call git clone --branch 0.0.1 git@github.com:AlephVault/unity-layout.git ..\unity-layout
call git clone --branch 0.0.2 git@github.com:AlephVault/unity-menu-actions.git ..\unity-menu-actions
call git clone --branch 0.0.2 git@github.com:AlephVault/unity-binary.git ..\unity-binary
call git clone --branch 0.0.6 git@github.com:AlephVault/unity-meetgard.git ..\unity-meetgard
call git clone --branch 0.0.5 git@github.com:AlephVault/unity-meetgard-auth.git ..\unity-meetgard-auth
call git clone --branch 0.0.3 git@github.com:AlephVault/unity-meetgard-scopes.git ..\unity-meetgard-scopes
call git clone --branch 0.0.2 git@github.com:AlephVault/unity-remotestorage.git ..\unity-remotestorage
call git clone --branch 0.0.1 git@github.com:AlephVault/unity-ipfs.git ..\unity-ipfs
call git clone --branch 0.0.1 git@github.com:AlephVault/unity-deeplinks.git ..\unity-deeplinks
call git clone --branch 0.0.1 git@github.com:AlephVault/unity-evmgames-wallets.git ..\unity-evmgames-wallets
call git clone --branch 0.0.4 git@github.com:AlephVault/unity-evmgames-auth.git ..\unity-evmgames-auth
call git clone --branch 0.0.3 git@github.com:AlephVault/unity-evmgames-livecache.git ..\unity-evmgames-livecache
call git clone --branch 0.0.2 git@github.com:AlephVault/unity-evmgames-localstorage.git ..\unity-evmgames-localstorage
call git clone --branch 0.0.2 git@github.com:AlephVault/unity-evmgames-contracts.git ..\unity-evmgames-contracts
call git clone --branch 0.0.2 git@github.com:AlephVault/unity-evmgames-bridge-contract.git ..\unity-evmgames-bridge-contract
call git clone --branch 0.0.2 git@github.com:AlephVault/unity-evmgames-deeplinks.git ..\unity-evmgames-deeplinks
call git clone --branch 4.19.2 https://github.com/Nethereum/Nethereum.Unity.git ..\Nethereum.Unity
call git clone --branch 4.19.3 https://github.com/Nethereum/Nethereum.Unity.WalletConnect.git ..\Nethereum.Unity.WalletConnect

